spring:
  application:
    name: service-discovery

server:
  port: 8081

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/